# 配列

## 生成

In [2]:
import numpy as np

np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [2]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### np.array(range()) 略して np.arange()

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### reshape 配列の形を変える

In [3]:
np.arange(27).reshape(3, 3, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

### size 要素数を知る

In [4]:
np.arange(12).size

12

### zeros 0 のみの配列

In [5]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

### ones 1 のみの配列

In [6]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

### empty 空の配列

In [7]:
np.empty(5)

array([ 0.,  0.,  0.,  0.,  0.])

### random 乱数配列（分布はメソッドチェーンで指定）

#### randn 標準正規分布

In [8]:
np.random.randn(5)

array([-0.26466972, -1.57498915,  0.30466119, -1.00253906,  0.11253325])

#### uniform 一様分布

In [9]:
np.random.uniform(10)

5.030633019265764

#### normal 正規分布

In [10]:
np.random.normal(5)

4.956251854427251

### permutation 要素並び替え（shuffle は破壊的）

In [11]:
np.random.permutation(5)

array([0, 4, 3, 1, 2])

### identity 単位行列

In [12]:
np.identity(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])