# 配列

## 生成

In [17]:
import numpy as np

np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [2]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### np.array(range()) 略して np.arange()

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### reshape 配列の形を変える

In [3]:
np.arange(27).reshape(3, 3, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

### size 要素数を知る

In [4]:
np.arange(12).size

12

### zeros 0 のみの配列

In [5]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

### ones 1 のみの配列

In [6]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

### empty 空の配列

In [7]:
np.empty(5)

array([ 0.,  0.,  0.,  0.,  0.])

### random 乱数配列（分布はメソッドチェーンで指定）

#### randn 標準正規分布

In [8]:
np.random.randn(5)

array([-0.26466972, -1.57498915,  0.30466119, -1.00253906,  0.11253325])

#### uniform 一様分布

In [9]:
np.random.uniform(10)

5.030633019265764

#### normal 正規分布

In [10]:
np.random.normal(5)

4.956251854427251

### permutation 要素並び替え（shuffle は破壊的）

In [11]:
np.random.permutation(5)

array([0, 4, 3, 1, 2])

### identity 単位行列

In [13]:
np.identity(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

## 加工

### hstack 配列を右にくっつける 

In [26]:
a = np.arange(6).reshape(2, 3)
b = np.arange(6, 12).reshape(2, 3)

np.hstack([a, b])

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### vstack 配列を下にくっつける

In [27]:
a = np.arange(6).reshape(2, 3)
b = np.arange(6, 12).reshape(2, 3)

np.vstack([a, b])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### 配列のスライス

In [34]:
np.arange(12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### 行を抽出

In [32]:
a = np.arange(12).reshape(3, 4)
a[1, :]

array([4, 5, 6, 7])

#### 列を抽出

In [33]:
a = np.arange(12).reshape(3, 4)
a[:, 1]

array([1, 5, 9])

### 特定条件に合う値を別の値に置き換える

In [48]:
a = np.arange(12).reshape(3, 4)
print(a)

a[a % 2 == 0]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 0,  2,  4,  6,  8, 10])

In [49]:
a = np.arange(12).reshape(3, 4)
print(a)

a[a % 2 == 0] = -1
a

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[-1,  1, -1,  3],
       [-1,  5, -1,  7],
       [-1,  9, -1, 11]])

### 配列のコピー

#### shallow copy

In [55]:
a = np.arange(6).reshape(2, 3)
b = a

# コピー先を変更
b[0, 1] = 100

# コピー元も変更される
a

array([[  0, 100,   2],
       [  3,   4,   5]])

#### deep copy

In [56]:
a = np.arange(6).reshape(2, 3)
b = a.copy()

# コピー先を変更
b[0, 1] = 100

# コピー元は変更されない
a

array([[0, 1, 2],
       [3, 4, 5]])

## 演算 

### 単純な四則演算

In [60]:
a = np.arange(10).reshape(2, 5)
a + 100

array([[100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109]])

In [64]:
a ** 2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [63]:
np.log(a + 1)

array([[ 0.        ,  0.69314718,  1.09861229,  1.38629436,  1.60943791],
       [ 1.79175947,  1.94591015,  2.07944154,  2.19722458,  2.30258509]])

In [65]:
np.sum(a)

45

#### axis=0 列ごとの和

In [66]:
np.sum(a, axis = 0)

array([ 5,  7,  9, 11, 13])

#### axis=1 行ごとの和

In [67]:
np.sum(a, axis = 1)

array([10, 35])

### 行列同士の計算

In [76]:
a = np.arange(6).reshape(2, 3)
b = np.arange(6, 12).reshape(2, 3)

In [77]:
a + b

array([[ 6,  8, 10],
       [12, 14, 16]])

In [78]:
a * b

array([[ 0,  7, 16],
       [27, 40, 55]])

In [79]:
a ** b

array([[       0,        1,      256],
       [   19683,  1048576, 48828125]])

In [80]:
a - b

array([[-6, -6, -6],
       [-6, -6, -6]])

In [81]:
a / b

array([[ 0.        ,  0.14285714,  0.25      ],
       [ 0.33333333,  0.4       ,  0.45454545]])

### 行列の積（ベクトルの内積）

#### 行列の積（1次元配列の時は内積）

In [89]:
a = np.arange(4)
b = np.arange(4, 8)

In [90]:
a.dot(b)

38

In [94]:
a = np.arange(6).reshape(2, 3)
b = np.arange(6).reshape(3, 2)

In [95]:
a.dot(b)

array([[10, 13],
       [28, 40]])

#### 転置行列

In [98]:
a = np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [99]:
a.T

array([[0, 3],
       [1, 4],
       [2, 5]])

#### 行列式（結果が 0 でなければ逆行列が存在する）

In [108]:
a = np.arange(1, 10).reshape(3, 3)
np.linalg.det(a)

-9.5161973539299405e-16

#### 逆行列

In [109]:
np.linalg.inv(a)

array([[  3.15251974e+15,  -6.30503948e+15,   3.15251974e+15],
       [ -6.30503948e+15,   1.26100790e+16,  -6.30503948e+15],
       [  3.15251974e+15,  -6.30503948e+15,   3.15251974e+15]])

#### 固有値と固有ベクトル

In [110]:
la, v = np.linalg.eig(a)

In [111]:
# 固有値
la

array([  1.61168440e+01,  -1.11684397e+00,  -9.75918483e-16])

In [113]:
# 固有ベクトル
v

array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]])